export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  SERVICE_OWNER = 'SERVICE_OWNER',
}

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  CLOSED = 'CLOSED',
}

export enum ReservationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED_BY_CUSTOMER = 'CANCELLED_BY_CUSTOMER',
  CANCELLED_BY_PROVIDER = 'CANCELLED_BY_PROVIDER',
  CHANGE_REQUESTED_BY_CUSTOMER = 'CHANGE_REQUESTED_BY_CUSTOMER',
  CHANGE_REQUESTED_BY_PROVIDER = 'CHANGE_REQUESTED_BY_PROVIDER',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
  EXPIRED = 'EXPIRED',
}

export enum ServiceMode {
  SOLO = 'SOLO',
  MULTI = 'MULTI',
}

export enum JoinRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationType {
  RESERVATION_RECEIVED = 'RESERVATION_RECEIVED',
  RESERVATION_CONFIRMED = 'RESERVATION_CONFIRMED',
  RESERVATION_REJECTED = 'RESERVATION_REJECTED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  RESERVATION_CHANGE_REQUESTED = 'RESERVATION_CHANGE_REQUESTED',
  UPCOMING_APPOINTMENT = 'UPCOMING_APPOINTMENT',
  DELAY_STATUS = 'DELAY_STATUS',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  SYSTEM = 'SYSTEM',
}

export enum VisibilityLabel {
  COMMON = 'COMMON',
  VIP = 'VIP',
  BEST_OF_MONTH = 'BEST_OF_MONTH',
  SPONSORED = 'SPONSORED',
  FEATURED = 'FEATURED',
}

export enum ReviewTargetType {
  SERVICE = 'SERVICE',
  PROVIDER = 'PROVIDER',
  BRAND = 'BRAND',
}

export enum CompletionMethod {
  MANUAL = 'MANUAL',
  QR = 'QR',
}
